In [51]:
from tkinter import *
from tkinter import filedialog
from PIL import ImageTk,Image
import imutils
import cv2
import numpy as np

In [52]:
def checkAffine(image, matrix):
    print(matrix)
    # А11 / А22 близко к единице - perserve scaling
    # A11 > 0, A22 > 0 - no reflecting
    if matrix[0][0] <= 0 or matrix[1][1] <= 0: return False 
    # нужны ограничения для A12 и A21 - restrict shearing - спросить АВ

    #нужны ограничения угла наклона - спросить АВ

    # Детерминант матрицы преобразования. Если он < 0 то преобразование точно не сохраняет ориентацию,
    # Но пусть доп. условие что детерминант обязан быть больше 0.5
    determinant = matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]
    print("determinant: ", determinant)
    
    if np.fabs(determinant - 1) > 0.5: return False
    else: return True

def stitch_pair(origin, addition, distance):
    padtop = addition.shape[1]
    padbottom = 0
    padleft = 250
    padright = 250
    origin = cv2.copyMakeBorder(origin, padtop, padbottom, padleft, padright, cv2.BORDER_CONSTANT, (0,0,0))

    sift = cv2.SIFT_create()
    _, mask = cv2.threshold(cv2.cvtColor(origin, cv2.COLOR_BGR2GRAY), 10, 255, cv2.THRESH_BINARY)

    ratio = (origin.shape[0] - padtop - padbottom) / addition.shape[0]
    if ratio > 1.5:
        #mask[int(padtop+addition.shape[0]):,:] = 0
        mask[int(padtop+(origin.shape[0]-padtop-padbottom)/ratio):,:] = 0
    cv2.imwrite("mask.png", mask)
     
    kp_o, desc_o = sift.detectAndCompute(origin, mask)
    
    _, mask = cv2.threshold(cv2.cvtColor(addition, cv2.COLOR_BGR2GRAY), 10, 255, cv2.THRESH_BINARY)
    kp_a, desc_a = sift.detectAndCompute(addition, mask)

    bf = cv2.BFMatcher()
    matches = bf.match(desc_o, desc_a)
    # If no matches were found at all
    if len(matches)==0: 
        return False, origin
    
    matches = sorted(matches, key = lambda x:x.distance)
    '''
    out = cv2.drawMatches(origin,kp_o,addition,kp_a,matches[:len(matches)],None,flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)
    cv2.imshow("matches", out)
    cv2.waitKey()
    cv2.destroyAllWindows()
    '''
    src_points = np.float32([kp_a[m.trainIdx].pt for m in matches]).reshape(-1,1,2)
    dst_points = np.float32([kp_o[m.queryIdx].pt for m in matches]).reshape(-1,1,2)

    ### add distance enforcing
    # Пусть ширина addition 4.5 м
    distance = addition.shape[1] * distance / 4.5
    fake_points_src = np.float32([
        [[origin.shape[1]//2, 50]],
        [[origin.shape[1]//2 - 50, 25]],
        [[origin.shape[1]//2 + 50, 25]]
    ])
    fake_points_dst = np.float32([
        [[origin.shape[1]//2, 50 + distance]],
        [[origin.shape[1]//2 - 50, 25 + distance]],
        [[origin.shape[1]//2 + 50, 25 + distance]]
    ])
    src_points = np.append(src_points, np.float32(fake_points_src), axis=0)
    dst_points = np.append(dst_points, np.float32(fake_points_dst), axis=0)
    ###
    
    h, _ = cv2.estimateAffinePartial2D(src_points, dst_points)
    if checkAffine(addition, h):
        flag = True
        warp = cv2.warpAffine(addition, h, (origin.shape[1],origin.shape[0]))
        _, mask = cv2.threshold(cv2.cvtColor(warp, cv2.COLOR_BGR2GRAY), 1, 255, cv2.THRESH_BINARY_INV)
    
        output = cv2.bitwise_and(origin, origin, mask=mask)
        output = output + warp
    else:
        fake_points_src = np.append(fake_points_src, src_points[:len(src_points)//2], axis=0)
        fake_points_dst = np.append(fake_points_dst, dst_points[:len(dst_points)//2], axis=0)
        h, _ = cv2.estimateAffinePartial2D(np.float32(fake_points_src), np.float32(fake_points_dst))
        flag = False
        warp = cv2.warpAffine(addition, h, (origin.shape[1],origin.shape[0]))
        _, mask = cv2.threshold(cv2.cvtColor(warp, cv2.COLOR_BGR2GRAY), 1, 255, cv2.THRESH_BINARY_INV)
    
        output = cv2.bitwise_and(origin, origin, mask=mask)
        output = output + warp
        '''
        flag = False
        print("using origin")
        output = origin.copy()
        '''
    
    _, mask = cv2.threshold(cv2.cvtColor(output, cv2.COLOR_BGR2GRAY), 1, 255, cv2.THRESH_BINARY)
    contours, _ = cv2.findContours(mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
    x,y,w,h = cv2.boundingRect(contours[0])
    
    return flag, output[y:y+h, x:x+w]

In [53]:
def checkPerspective(image, matrix):
    print(matrix)
    # Первая проверка -- отношение левой и правой стороны после трансформации 
    points = []
    new_points = []
    nw = (0,0)
    points.append(nw)
    ne = (image.shape[1],0)
    points.append(ne)
    se = (image.shape[1], image.shape[0])
    points.append(se)
    sw = (0, image.shape[0])
    points.append(sw)
    
    left_original = np.sqrt((nw[0] - sw[0])**2 + (nw[1] - sw[1])**2)
    right_original = np.sqrt((ne[0] - se[0])**2 + (ne[1] - se[1])**2)
    top_original = np.sqrt((nw[0] - ne[0])**2 + (nw[1]-ne[1])**2)
    bottom_original = np.sqrt((sw[0] - se[0])**2 + (sw[1] - se[1])**2)
    
    for p in points:
        alpha = matrix[2][0] * p[0] + matrix[2][1] * p[1] + matrix[2][2]
        y = (matrix[1][0] * p[0] + matrix[1][1] * p[1] + matrix[1][2] ) / alpha
        x = (matrix[0][0] * p[0] + matrix[0][1] * p[1] + matrix[0][2] ) / alpha
        new_points.append((x,y))
    new_nw = new_points[0]
    new_ne = new_points[1]
    new_se = new_points[2]
    new_sw = new_points[3]
    
    ### distance that every point travelled
    print(np.sqrt((new_nw[0] - nw[0])**2 + (new_nw[1] - nw[1])**2))
    print(np.sqrt((new_ne[0] - ne[0])**2 + (new_ne[1] - ne[1])**2))
    print(np.sqrt((new_se[0] - se[0])**2 + (new_se[1] - se[1])**2))
    print(np.sqrt((new_sw[0] - sw[0])**2 + (new_sw[1] - sw[1])**2))
    
    left_converted = np.sqrt((new_nw[0] - new_sw[0])**2 + (new_nw[1] - new_sw[1])**2)
    right_converted = np.sqrt((new_ne[0] - new_se[0])**2 + (new_ne[1] - new_se[1])**2)
    top_converted = np.sqrt((new_nw[0] - new_ne[0])**2 + (new_nw[1] - new_ne[1])**2)
    bottom_converted = np.sqrt((new_sw[0] - new_se[0])**2 + (new_sw[1] - new_se[1])**2)
    
    # Если модуль (отношение - 1) меньше чем 0.2, то вторая проверка:
    print("left right ratio: ", left_converted / right_converted)
    print("top bottom ratio: ", top_converted / bottom_converted)
    
    # Число обусловленности для плохих преобразований очень большое
    print("condition: ", np.linalg.cond(matrix[:,:2]))
    if np.linalg.cond(matrix[:, :2]) >= 10: return False
    if np.fabs(left_converted/right_converted - 1) >= 0.3: return False
    if np.fabs(top_converted/bottom_converted - 1) >= 0.3: return False
    
    # Детерминант матрицы преобразования. Если он < 0 то преобразование точно не сохраняет ориентацию,
    # Но пусть доп. условие что детерминант обязан быть больше 0.5
    determinant = matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]
    print("determinant: ", determinant)
    
    if (determinant < 0): return False
    else: return True

def stitch_pair_legacy(origin, addition):
    padtop = addition.shape[1]
    padbottom = 0
    padleft = 0
    padright = 0
    origin = cv2.copyMakeBorder(origin, padtop, padbottom, padleft, padright, cv2.BORDER_CONSTANT, (0,0,0))

    sift = cv2.SIFT_create()
    _, mask = cv2.threshold(cv2.cvtColor(origin, cv2.COLOR_BGR2GRAY), 10, 255, cv2.THRESH_BINARY)
    kp_o, desc_o = sift.detectAndCompute(origin, mask)
    
    _, mask = cv2.threshold(cv2.cvtColor(addition, cv2.COLOR_BGR2GRAY), 10, 255, cv2.THRESH_BINARY)
    kp_a, desc_a = sift.detectAndCompute(addition, mask)

    bf = cv2.BFMatcher()
    matches = bf.match(desc_o, desc_a)
    # If no matches were found at all
    if len(matches)==0: 
        return False, origin
    
    matches = sorted(matches, key = lambda x:x.distance)
    
    out = cv2.drawMatches(origin,kp_o,addition,kp_a,matches[:len(matches)],None,flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)
    cv2.imshow("matches", out)
    cv2.waitKey()
    cv2.destroyAllWindows()
    
    src_points = np.float32([kp_a[m.trainIdx].pt for m in matches]).reshape(-1,1,2)
    dst_points = np.float32([kp_o[m.queryIdx].pt for m in matches]).reshape(-1,1,2)
    
    h, status = cv2.findHomography(src_points, dst_points, cv2.RANSAC)
    if (checkPerspective(addition, h)):
        flag = True
        warp = cv2.warpPerspective(addition, h, (origin.shape[1],origin.shape[0]))
        _, mask = cv2.threshold(cv2.cvtColor(warp, cv2.COLOR_BGR2GRAY), 1, 255, cv2.THRESH_BINARY_INV)
    
        output = cv2.bitwise_and(origin, origin, mask=mask)
        output = output + warp
    else:
        print("Using origin")
        output = origin.copy()
        flag = False

    _, mask = cv2.threshold(cv2.cvtColor(output, cv2.COLOR_BGR2GRAY), 1, 255, cv2.THRESH_BINARY)
    contours, _ = cv2.findContours(mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
    x,y,w,h = cv2.boundingRect(contours[0])
    
    return flag, output[y:y+h, x:x+w]    

In [54]:
paths = []
paths = filedialog.askopenfilenames(initialdir="/home/raz/src/indor/imagestitcher/Images/", title="Select file",filetypes=(("PNG",".png"),("JPEG",".jpg .jpeg")))
print(len(paths))

N_IMAGES = len(paths)
images = []
for p in paths:
    images.append(cv2.imread(p))

84


In [55]:
process = images[0].copy()
helper = []
helperd = []

i = 1
dis = 3
dd = dis
while (i < N_IMAGES):
    print(i)
    status, process = stitch_pair(process, images[i], dis)
    if status:
        i += 1
        dis += 3
    else:
        '''
        helper.append(process.copy())
        cv2.imwrite("/home/raz/src/indor/imagestitcher/Images/debug/"+str(i)+".png", process)
        i += 1
        dis += 3
        '''
        helper.append(process.copy())
        helperd.append(dd)
        cv2.imwrite("/home/raz/src/indor/imagestitcher/Images/debug/"+str(i)+".png", process)
        i -= 1
        dis -= 3
        process = images[i].copy()
        dd = dis
        
#process = helper[0]
#for i in range(len(helper)):
#    _, process = stitch_pair(process, helper[i], helperd[i])

cv2.imwrite("/home/raz/src/indor/imagestitcher/Images/debug/Result.png", process)
cv2.imshow("Result", process)
cv2.waitKey(0)    
cv2.destroyAllWindows()

1
[[ 9.81108230e-01  2.04719015e-02  2.47287687e+02]
 [-2.04719015e-02  9.81108230e-01  6.48802794e+02]]
determinant:  0.9629924581604159
2
[[ 9.86553127e-01  4.14221772e-02  2.33003642e+02]
 [-4.14221772e-02  9.86553127e-01  6.46325817e+02]]
determinant:  0.9750028687020954
3
[[ 9.80374319e-01  3.68325527e-02  2.50486290e+02]
 [-3.68325527e-02  9.80374319e-01  6.52626739e+02]]
determinant:  0.9624904417931193
4
[[ 9.71641529e-01  3.00151894e-02  2.55875667e+02]
 [-3.00151894e-02  9.71641529e-01  6.45404257e+02]]
determinant:  0.9449881722915272
5
[[ 9.60733797e-01  7.81098654e-02  2.40508384e+02]
 [-7.81098654e-02  9.60733797e-01  6.76386526e+02]]
determinant:  0.9291105804599594
6
[[ 9.51865313e-01  8.43923901e-02  2.47144862e+02]
 [-8.43923901e-02  9.51865313e-01  6.92145356e+02]]
determinant:  0.913169650120996
7
[[ 9.30046577e-01  7.66350589e-02  2.56994815e+02]
 [-7.66350589e-02  9.30046577e-01  7.00792137e+02]]
determinant:  0.8708595675104209
8
[[ 9.12768370e-01  6.96221738e-02